### ISSUE TITLE
Provide install instructions for RHEL / CentOS

### ISSUE THREAD

**Issue by Trefex** [monarc-project/MonarcAppFO#136]

**Comment by ral88** [comment]
hi,

this is how I installed monarc v2.7.4 on rh7. it should be similar on centos. improvements welcome.

software repositories & packages:

- install apache (httpd), mariadb, mod_ssl & dependencies from the standard redhat repositories

- install Remi's rpm repository for rh7
# yum install https://rpms.remirepo.net/enterprise/remi-release-7.rpm

- install the epel repo - extra packages for enterprise linux 7
# yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

- install php7.2, required modules & dependencies from Remi's repository:
php72.x86_64 php72-php.x86_64 php72-php-gd.x86_64 php72-php-mysqlnd.x86_64 php72-php-mbstring.x86_64 php72-php-pear.noarch php72-php-pecl-apcu.x86_64 php72-php-xml.x86_64 php72-php-intl.x86_64 php72-php-pecl-imagick.x86_64 php72-php-pecl-zip.x86_64

- install npm, nodejs-grunt-cli & dependencies


mariadb:

- add the following line to server.cnf (/etc/my.cnf.d/server.cnf) otherwise you may get an error when initializing the database
[mariadb]
max_allowed_packet=8M

- start the server and create the databases (in the interpreter)
CREATE DATABASE monarc_cli DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE monarc_common DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

- initialize the database
# mysql -u root -p monarc_common < db-bootstrap/monarc_structure.sql
# mysql -u root -p monarc_common < db-bootstrap/monarc_data.sql

- create a database user for monarc (in the interpreter)
create user 'monarc'@'localhost' identified by 'password';
grant create, delete, insert, select, update, drop, alter on monarc_common.* to 'monarc'@'localhost';
grant create, delete, insert, select, update, drop, alter on monarc_cli.* to 'monarc'@'localhost';


install monarc:

- create the subdirectory monarc under apache documentroot (/var/www/html/) and cd to it

- if you're behind an explicit proxy, set the env variables and configure git to use the proxy
$ export HTTP_PROXY=<proxy>:<port>
$ export HTTPS_PROXY=<proxy>:<port>
$ export HTTP_PROXY_REQUEST_FULLURI=0
$ export HTTPS_PROXY_REQUEST_FULLURI=0
$ git config --global http.proxy http://<proxy>:<port>

- add php to $PATH
$ export PATH=$PATH:/opt/remi/php72/root/usr/bin:/opt/remi/php72/root/usr/sbin

- clone the repository and invoke composer
$ git clone https://github.com/monarc-project/MonarcAppFO.git fo
$ cd fo
# /opt/remi/php72/root/usr/bin/php ./composer.phar self-update
$ /opt/remi/php72/root/usr/bin/php ./composer.phar install -o

- backend
$ mkdir module
$ cd module/
$ ln -s ./../vendor/monarc/core MonarcCore
$ ln -s ./../vendor/monarc/frontoffice MonarcFO

- frontend
$ mkdir node_modules
$ cd node_modules
$ git clone https://github.com/monarc-project/ng-client.git ng_client
$ git clone https://github.com/monarc-project/ng-anr.git ng_anr

- set up the database connection:
$ cd /var/www/html/monarc/fo/config/autoload/
$ cp local.php.dist local.php
$ diff local.php.dist local.php
14c14
<  $appdir = getenv('APP_DIR') ? getenv('APP_DIR') : '/var/lib/monarc/fo';
---
>  $appdir = getenv('APP_DIR') ? getenv('APP_DIR') : '/var/www/html/monarc/fo';
27,28c27,28
<                     'user' => 'root',
<                     'password' => 'password',
---
>                     'user' => 'monarc',
>                     'password' => 'password',
35,36c35,36
<                     'user' => 'root',
<                     'password' => 'password',
---
>                     'user' => 'monarc',
>                     'password' => 'password',

- update monarc (including npm config for explicit proxy)
$ npm config set proxy http://<proxy>:<port>
$ npm config set https-proxy http://<proxy>:<port>
$ cd /var/www/html/monarc/fo
$ ./scripts/update-all.sh

- create initial user
$ php ./vendor/robmorgan/phinx/bin/phinx seed:run -c ./module/MonarcFO/migrations/phinx.php


configure apache

- set file ownership for monarc installation
# cd /var/www/html/
# chown -R apache:apache monarc

- configure virtual host
# cd /etc/httpd/conf.d/
# vim virtualhost.conf

<VirtualHost *:80>
    ServerName monarc.<domain>
    DocumentRoot /var/www/html/monarc/fo/public

    <Directory /var/www/html/monarc/fo/public>
        DirectoryIndex index.php
        AllowOverride All
        Require all granted
    </Directory>

    SetEnv APPLICATION_ENV "development"
</VirtualHost>

**Comment by cedricbonhomme** [comment]
nice, thank you for this. It seems to be precise enough to be added in the documentation of the repository.

**Comment by KonzeptAcht** [comment]
Thanks for this nice work, but I get an empty Page after installation. The virtualhost file seems to be correct. index.php ist loaded and php runs correct. But the index.php doesn_t load any content (Only favicon as tab icon). Database Login also works fine.

Does anyone have an idea for help?

**Comment by jerolomb** [comment]
Hello,

Do you have some errors in the browser's console ? Or in the log php ? 

Typically, the blank page is due to an error of DB connection. The application can't arrive to connect to the Database. Do you have put the right credential in the local.php ? ./config/autoload/local.php

**Comment by cedricbonhomme** [comment]
@ral88 we have pushed your instructions in the master branch. thank you!

**Comment by Gunstick** [comment]
there is no composer.phar file in the repo.

**Comment by KonzeptAcht** [comment]
Hey @Gunstick,

if you have successfully installed the composer package, you can simply leave out the ".phar" and do 

`composer` self-update
composer install -o 

Installation: https://getcomposer.org/

In my experience you need Version >= 1.9.0

**Comment by ruslanbaidan** [comment]
Absolutely, composer.phar is not needed for the dependencies installation.
Thank you for your comment @KonzeptAcht.

Just to add, the link to install composer locally or globally is here:
https://getcomposer.org/download/

I would also recommend to use the latest version of composer 2.0 as it is just faster.

**Comment by KonzeptAcht** [comment]
@ruslanbaidan If you revise the installation instructions: We currently also have a completely translated version on our website. If you want to link it to the training material or add it to the git. https://www.konzeptacht.de/monarc-installation-ubuntu-18-04

In addition, we have recently tested and included the 20..04.

**Comment by ruslanbaidan** [comment]
@KonzeptAcht ,
Thank you for the update.
We will definitely add the reference.

The new instructions to the installation steps will be also added very soon along with the new version of the tool.
