### ISSUE TITLE
Error loading my.monarc.lu

### ISSUE THREAD

**Issue by sarah-peter** [monarc-project/MonarcAppFO#147]
Hello,

unfortunately me and my colleague have again an error when loading our risk analysis in my.monarc.lu. After signing in we see the following error message pop up and the list doesn't show any of our risk analyses.

`An error occurred while fetching api/client-anr: An exception occurred while executing 'SELECT t0.uuid AS uuid_1, t0.label1 AS label1_2, t0.label2 AS label2_3, t0.label3 AS label3_4, t0.label4 AS label4_5, t0.creator AS creator_6, t0.created_at AS created_at_7, t0.updater AS updater_8, t0.updated_at AS updated_at_9, t0.anr_id AS anr_id_10 FROM referentials t0 WHERE t0.anr_id = ?' with params [1]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'lcsbuni.referentials' doesn't exist (500)`

**Comment by cedricbonhomme** [comment]
Hi,

We are currently deploying version 2.8.0 of MONARC in our environment. And so we have to update something like 100 data bases ;-)
For your instance, it will be fixed in minutes.

**Comment by sarah-peter** [comment]
Ok, no problem :-)

**Comment by Trefex** [comment]
@cedricbonhomme thanks we had a bad luck to open at this moment then :)

Is there somewhere an announcement where we can see such updates before hand?

**Comment by cedricbonhomme** [comment]
Actually no. But we will implement some measures for the next releases when we will update our production server. Yesterday a certain number of people, way more than usual, were connected to the service in order to test the release. And the DBs were updated in almost the same time.
If we need to announce something for this, this will be done via Twitter. We would like to not use a maintenance page...
