### ISSUE TITLE
Translation into other languages

### ISSUE THREAD

**Issue by keoni161** [monarc-project/MonarcAppFO#192]
Hi,
I would like to translate the app into a new language. How would I go about adding a translation for the frontend and the database?
Thank you
Claudiu

**Comment by ruslanbaydan** [comment]
Hi Claudiu,

Thank you for your desire to contribute to Monarc project.

To translate the frontend part we use .po files, you can find them here:
https://github.com/monarc-project/ng-client/tree/master/po
To add a new system language, some parts of the project are required modifications as well as new columns in the database needs to be created. You can have an idea how many DB tables have the translations' related fields:
https://github.com/monarc-project/MonarcAppFO/blob/master/db-bootstrap/monarc_structure.sql#L59-L66 ...

We have plans to improve the translations management and make the process simple. Currently it is on hold (https://github.com/monarc-project/MonarcAppFO/wiki/Roadmap), but I am sure we will came back to the idea soon.

What is the language you would like to translate on?

Thank you.

**Comment by keoni161** [comment]
Hi thank. you
I will get started.
Romanian is the language

**Comment by ruslanbaydan** [comment]
Hi,
That's good.
Could you tell if you already a Monarc user?
How do you have/planning to have Monarc installed (on your premises or instance on our side)?

If it is for a new instance, we would propose you to prepare Rumanian translations for the DB in the following initial data migration file: 
https://github.com/monarc-project/MonarcAppFO/blob/master/db-bootstrap/monarc_data.sql
And place your language on the place of Dutch one (label4, description4) for every tables' fields.

Thank you.

**Comment by valyy2003** [comment]
Hi,
What happened with the romanian translation?
The FO seems to be translated, we just need to focus on the database?

**Comment by ruslanbaidan** [comment]
Hello,

What I could see from my side the UI in Romanian looks pretty good.

Regarding the database objects translation it is a tricky thing for the moment, as I told before, it is possible to do so with use manarc_data.sql.
But there is an another possibility to do this by exporting the whole analysis that you prepared for example in english (or other language) and work with the exported .json file.
It would be necessary to replace or add labelX, nameX and descriptionX, where X - is the language number you would like to use as Romanian.
By default: 1 - french, 2 - english, 3 - german, 4 - dutch.
**For example.**
If you exported an analysis that was created in English, you could keep label2 as they are and replace/set all the label3, name3, description3 values in the json to the Romanian translated values.
As far as German language was used in our example (numer 3), when an analysis is created, the german language is always used. And the modified json file could be used as a template every time to import into the new analysis.
What is important in this approach that all the required library assets have to be added to the analysis before export of the .json otherwise they will not be presented in the file. After the import they can be detached, if not needed.

Both approaches are working, and we have successful experience informed by some of Monarc users.

Thank you.
