### ISSUE TITLE
fortify the update procedure

### ISSUE THREAD

**Issue by eurodude** [monarc-project/MonarcAppFO#194]
It looks like some people seem to be able to break data after the updates. We need to verify if we can create an update system that will verify integrety of all data at multiple stages during the update... 

Maybe this is a permission thing on files or an "Alter Table" user permission thing or simply a cache thing. So we should check all of these before beginning the updates.

**Comment by ruslanbaidan** [comment]
I think it was an age case when we did the upgrade and some migration script impacted the users permissions or access to some of the tables or directories.
We did not have such problems since the time and for the future we need to carefully validate each release migrations which suppose to be executed and providing required permissions to the file systems in case of new directories creation or other needs.
However the last point is mostly related to the ansible tasks.
