### ISSUE TITLE
Lost operational risks of assets in library after a snapshot

### ISSUE THREAD

**Issue by jfrocha** [monarc-project/MonarcAppFO#25]
Issue after creation a snapshot. Then in current risk analysis, no operational risk of assets in the library.
If you restore snapshot, the operational risks come back.

**Comment by jfrocha** [comment]
The bug could be here:

_MonarcFO/Service/AnrService.php:492_

                foreach ($rolfRisk->tags as $key => $tag) {
                    if (!empty($rolfTagsNewIds[$tag->id])) {
                        $newRolfRisk->setTag($key, $rolfTagsNewIds[$tag->id]);
                    }
                }
                $this->get('rolfRiskCliTable')->save($newRolfRisk,false);
                $rolfRisksNewIds[$rolfRisk->id] = $newRolfRisk;
            }

**Comment by cedricbonhomme** [comment]
Indeed, this makes sense.

I am wondering if we loose the value of *$rolfRisksNewIds* (https://github.com/monarc-project/zm-client/blob/master/src/MonarcFO/Service/AnrService.php#L498). This value seems to be only used here (https://github.com/monarc-project/zm-client/blob/master/src/MonarcFO/Service/AnrService.php#L711) in order to set the property *RolfRisk* of the new *InstanceRiskOp*.
I am not sure.  I need to debug that.

**Comment by jfrocha** [comment]
Fixed.   
related commit : [f99248e](https://github.com/monarc-project/zm-client/commit/f99248e4efae044085c4b263bfb8a73ae02fe5b7)
