### ISSUE TITLE
Remove the category for operational risk

### ISSUE THREAD

**Issue by jerolomb** [monarc-project/MonarcAppFO#26]
The category of the operational risk is not use and usefull.

**Comment by cedricbonhomme** [comment]
Just to understand well, you mean this:
https://github.com/monarc-project/zm-core/blob/master/src/MonarcCore/Model/Entity/RolfRiskSuperClass.php#L52  ?

Which is related (setCategories) to the previous bug fix (here: https://github.com/monarc-project/zm-client/commit/f99248e4efae044085c4b263bfb8a73ae02fe5b7#diff-679b5cc365b0695f9b2458d8ac3c911aR496)

**Comment by cedricbonhomme** [comment]
For information, this issue is actually treated in:

backend:
- https://github.com/monarc-project/zm-client/commits/improvement/remove-categories-from-op-risks
- https://github.com/monarc-project/zm-core/commits/improvement/remove-categories-from-op-risks

frontend:
- https://github.com/monarc-project/ng-anr/commits/improvement/remove-categories-from-op-risks

**Comment by cedricbonhomme** [comment]
Actually working on the BO. Some new changes in:

https://github.com/monarc-project/zm-backoffice/commits/improvement/remove-categories-from-op-risks

https://github.com/monarc-project/ng-backoffice/commits/improvement/remove-categories-from-op-risks

**Comment by cedricbonhomme** [comment]
Done. No changes in ng-client.
