### ISSUE TITLE
UTF-8 Ecode Password Reset E-Mail

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#291]
**Is your feature request related to a problem? Please describe.**
We have done a translation of the password reset e-mail and now have problems with the German umlauts "äöüß...".

**Describe the solution you'd like**
UTF-8 Encoded E-Mail Sending

**Comment by cedricbonhomme** [comment]
Thank you, we will check if we are using UTF-8. And with [Quoted Printable character](https://tools.ietf.org/html/rfc2045#section-6.7), it is sometimes an issue with UTF-8 in emails.

Did you translate the following string ?
https://github.com/monarc-project/zm-core/blob/master/src/Service/PasswordService.php#L67-L73

Because it would be better to have this in a template...

**Comment by KonzeptAcht** [comment]
Yes, wie translated this lines and added the following to the bottom.
```<hr>
<p>Hallo,</p>
<p>Dies ist eine automatisch generierte E-Mail, bitte nicht antworten</p>
<p>Vielen Dank, dass Sie ein neues Passwort angefordert haben. Bitte best\xc3\xa4tigen Sie Ihre Anfrage, indem Sie auf den untenstehenden Link klicken:<br />
    <a href="$link"><strong>$link</strong></a>
</p>
<p>Falls Sie kein neues Passwort angefordert haben, bitten wir Sie, diese E-Mail zu ignorieren.</p>
<p>Mit freundlichen Gr\xc3\xbcssen,<br />KonzeptAcht Team</p>

**Comment by KonzeptAcht** [comment]
Can no longer reproduce the problem in the current version. Perhaps it was also a problem on our part in terms of configuration. Issue can be closed.

**Comment by ruslanbaidan** [comment]
Thank you for the feedback!
