### ISSUE TITLE
Error message when changing status of recommendation

### ISSUE THREAD

**Issue by Tichod** [monarc-project/MonarcAppFO#312]
**Describe the bug**
When clicking on the status button of a recommendation, an error message happens 

**To Reproduce**
1. Go to the  Knowledge base > Recommendations Sets.
2. Click on the status button of a recommendation
3. See error message (cf. screenshot attached).

**Expected behavior**
The help message content shouldn't be duplicated.

**Screenshots**
See attached
![2020_09_23-Formation_MONARC-000020](https://user-images.githubusercontent.com/18058781/94011395-95a1dc00-fda7-11ea-93e0-82993026d250.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04.4
| OS version (client)                   | Win10
| PHP version                             | 7.4.3
| MONARC version / git hash     | 2.9.16 (virtual machine)
| Browser                                    | Firefox 81.0 and Chrome 85.0.4183.121

**Additional context**
N/A

**Comment by cedricbonhomme** [comment]
I am not able to reproduce it with this information.
From your error message, it seems there is an issue related to the duedate attribute of a recommendation. Will investigate.

**Comment by ruslanbaidan** [comment]
We don't know what could be the initial manipulation steps with the recommendations, which led you to the issue appearance, because for us it works fine with use of the lates VM.
However some investigation of the error gave us an idea that "counterTreated" should not be modified by passing a value from Frontend side to update it. Even if it's an integer value. So we need to filter it out from the incoming request parameters.
The fix should help to solve the issue. We are going to do this in the next release.
