### ISSUE TITLE
Snapshot issue

### ISSUE THREAD

**Issue by gregorygrevin** [monarc-project/MonarcAppFO#313]
**Describe the bug**
Error message during a snapshot test, and the snapshot does not work 

**To Reproduce**
1. snapshot menu
2. create snapshot

Also, the error appears when I am trying to load ISO27002.

*Expected behavior**
Try to perform a snapshot 
**Screenshots**
 
![image](https://user-images.githubusercontent.com/9590506/95875288-28fc7a80-0d72-11eb-8513-99967ee6aa38.png)

**Desktop (please complete the following information):**
| Questions | Answers
|Create a snapshot |Error during analysis creation
| Type of issue : snapshot error
| OS version (server) : Ubuntu 18.04.5 LTS
| OS version (client) : Windows 10 1909, Browser Google Chrome  85.0.4183.121
| PHP version : PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS
| MONARC version / git hash : 2.9.16
| Browser : Firefox, Chrome

**Additional context**
We try to build an ‘out of box’ risk analysis from CASES template, and snapshot work perfectly
For the other risk analysis, we use also Cases template, and build an organization based on duplicated departments.

**Comment by gregorygrevin** [comment]
Hello,

I would like to know if you find anything for my issue. It is now 16 days that I opened the case.

Thank you,

**Comment by ruslanbaidan** [comment]
Hello,

In order to find help us to diagnose the issue, could you please provide the following information:
1. Do you use Monarc on our cloud, local VM or version installed on your server?
2. Do you have the error during creation of Snapshot or when you try to restore it? It's not clear based on the screenshot and your description.
3. Could you send us (info@cases.lu) a response error from your browser Console -> Network tab -> Response. To better find the exact request to backend you can clear your list of requests when after opening Snapshots popup, then click Create or Restore (depends on the issue occurence). We need the response error.

The case is that we can't reproduce the issue on our production. Creation and restoring Snapshots work well, but might be you have some special case with your analyse.

Thank you.

**Comment by ruslanbaidan** [comment]
Die to the outdated version use.
