### ISSUE TITLE
API Error in Webinterface after fresh install 

### ISSUE THREAD

**Issue by YRe4per** [monarc-project/MonarcAppFO#317]
**Describe the bug**
I have followed the installation procedure on your website: https://github.com/monarc-project/MonarcAppFO/blob/master/INSTALL/INSTALL.ubuntu1804.md

After installation I receive this error on the webinterface everytime the page is reloaded:
_An error occurred while fetching api/client-anr: 
Service with name "Monarc\FrontOffice\Stats\Provider\StatsApiProvider" 
could not be created. Reason: The following configuration options are 
missed in the config: "statsApi.baseUrl" (500)_

**Expected behavior**
When creating a new risk analysis it's not possible to fill in all fileds, for example selecting the language, the description or to create the analysis.

**Screenshots**
![2020-11-25 16_33_31-](https://user-images.githubusercontent.com/33641056/100249292-b0760580-2f3c-11eb-8ab8-23c74d5c6a8c.png)

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                            | Bug
| OS version (server)                  | Ubuntu 18.04.5
| OS version (client)                   | Win10
| PHP version                             | 7.2.24
| MONARC version / git hash     | 2.9.16 (lastest version downloaded today as described in the install manual)
| Browser                                    | Chrome, Edge

**Comment by ruslanbaidan** [comment]
Thank you for the report.

*Introduction*
This week we are performing a new release of Monarc, which had an impact on master branch.
The new release is not announced yet as the process is not finished yet.
There is a new feature which is coming in the release (Global Dashboard).

*Solution*
Your installation included the code of the feature implementation, however there is an external service to be configured if you would like to use it. The configuration description can be accessed here:
https://github.com/monarc-project/MonarcAppFO/blob/master/vagrant/bootstrap.sh#L202-L292
We are going to update the installation instructions, you referenced, with the link to the StatsService project readme:
https://github.com/monarc-project/stats-service/blob/master/README.md.
To be able to collect the stats from your instance you also need to configure a crontab. Here is the example of `crontab -e`:
`0 0 * * * /var/lib/monarc/fo/bin/console monarc:collect-stats`
You might need to see if it has to be run under a specific user for example `www-data`.

If you don't need, don't want to use the Global Dashboard feature, which is still under test mode and will be updated soon, we recommend you to add the following lines in your configuration file /var/lib/monarc/fo/config/autoload/local.php before the last closing brace `];`:
`
    'statsApi' => [
        'baseUrl' => 'http://127.0.0.1:5005',
        'apiKey' => '',
    ],
`

*Note:*
Very soon, we are going to improve the installation instructions in order to use a specific release tags for the new installations. That should avoid such issue as you faced.

**Comment by YRe4per** [comment]
Hello, thanks for your fast reply.

We would prefer to update monarc to the latest version once it is released, can you please include an upgrade method in the new installation instructions?

Note:
We tried to placeing the stats api line in  /var/lib/monarc/fo/config/autoload/local.php but it didn't work unfortunately. (it gave us the same error)

![2020-12-09 14_41_34-](https://user-images.githubusercontent.com/33641056/101637156-ab30b480-3a2c-11eb-802c-27acba926b3c.png)

![2020-12-09 14_36_17-](https://user-images.githubusercontent.com/33641056/101637013-73c20800-3a2c-11eb-891a-eb7b0959e72f.png)

**Comment by KonzeptAcht** [comment]
Hello @YRe4per,

have you deleted the cache after changing the local.php and restarted apache?

`rm -rf data/cache/*`
`rm -rf data/DoctrineORMModule/Proxy/*`
`rm -rf data/LazyServices/Proxy/*`
