### ISSUE TITLE
Provide proper manual for newcomers

### ISSUE THREAD

**Issue by siranen** [monarc-project/MonarcAppFO#34]
I cannot start Your app because there is no manual

**Comment by cedricbonhomme** [comment]
Hi,

You can test MONARC with the VirtualBox machine: http://monarc.lu/pages/download
If you need some help in order to configure the VM: http://monarc.lu/pages/trainings

You will also find some documentation about the tool (user guide) here:
http://monarc.lu/pages/documentation


If you prefer to install it from scratch, we have some documentation here:
https://github.com/monarc-project/MonarcAppFO/blob/master/INSTALL/INSTALL.ubuntu1704.md

You can also use the following script on your server:
https://github.com/monarc-project/monarc-packer/blob/master/scripts/bootstrap.sh
which assumes that you have a _monarc_ user (in the _sudo_ group) and a _monarc_ group on the system.
