### ISSUE TITLE
Laminas Invalid arguments or no arguments provided

### ISSUE THREAD

**Issue by dbarzin** [monarc-project/MonarcAppFO#460]
**Describe the bug**
Error during the update process from Monarc 2.11.1 to Monarc 2.12.3
After update impossible to log into Monarc.

**To Reproduce**

I have a instance of Monarc 2.11.1 downloaded as OVA from GitHub and running in a VM.

The instance has been updated with :

```
sudo apt update
sudo apt upgrade
```

The update process returns an error :

```
monarc@monarc:/var/lib/monarc/fo$ ./scripts/update-all.sh -c
...

Laminas application
Usage:

Reason for failure: Invalid arguments or no arguments provided
Laminas application
Usage:

Reason for failure: Invalid arguments or no arguments provided
Laminas application
Usage:

Reason for failure: Invalid arguments or no arguments provided
Done for ./config/autoload/local.php
```

**Expected behavior**
A working Monarc instance after update

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04 LTS
| OS version (client)                   | Win10
| PHP version                             | PHP 7.4
| MONARC version / git hash     | 2.11.1
| Browser                                    | Firefox

**Additional context**

**Comment by ruslanbaidan** [comment]
Hello,

Thank you for the report.

We never use `-c` option in the update-all.sh script, that's why there was an old way of the cache cleanup process.
We fixed it in [this commit](https://github.com/monarc-project/MonarcAppFO/commit/35a44c2b2e3c0b2b032d000f4db919d0a7c597ac#diff-9cd03651c4e18912c33a3a9b4d087c2373de6f7723d319e05b4e119b17193ad7R108-R110).
You could execute `git pull` in your project root to obtain the changes or run the script without the `-c` option and execute the cache cleanup (3 commands) manually.

**Comment by ruslanbaidan** [comment]
The option can be used, there was the fix provided.
