### ISSUE TITLE
Decrypting JSON files of a MONARC risk analysis

### ISSUE THREAD

**Issue by ThierryPGT** [monarc-project/MonarcAppFO#47]
Many of my clients would like to read the JSON extraction file of a MONARC analysis, in order to integrate it into other BIA (Business Impact Analysis) software.
It would be enough to have a simple interface:
 - Input : Encrypted JSON file and the password
 - Output : The JSON file in clear text.
What do you thing of taht ?
CU
Thierry

**Comment by cedricbonhomme** [comment]
This is an interesting proposition.

We can do it even simpler by just adding an option in the 'Export risk analysis' modal that will let the user directly download a clear JSON file.

This is quite easy to do. But I do not think our JSON follows any standard. So people would still need to use a tool to import the JSON file in a software such as Aris.
Is there a standard (kind of) that is actually used by other software like MONARC? If not, this can also be good for us.

Anyway, the idea to let the user get a clear JSON file is interesting.

**Comment by ThierryPGT** [comment]
It is not a problem that the JSON does not follow any standard, people know the destination software enough to write themselves import scripts and select the items they want to import.

Your proposal exactly meets expectations.
CU
Thierry

**Comment by cedricbonhomme** [comment]
Issue fixed in master with:
monarc-project/zm-core@339e57dcd6a42aa7ced415b7aae89b1d805112ce
monarc-project/zm-core@8d307b3dde5aedcbd5a4009c4a86998d286b9bd3

monarc-project/zm-client@38bf3f9c57874aa6f86769f296fad98e44a3f780
monarc-project/zm-client@021e8a2df1cc377fb23fe0332f134fbe73308ee6

monarc-project/zm-backoffice@ab8ebfe0eb8bcbc2058bdc4878ab4d36ce25e98d

monarc-project/ng-anr@c613274a2c1c7a3f7333e108ff7cadbe3f579fb5
monarc-project/ng-anr@9012cbd4067be5bce534f26308627ba6cf6f7151
